# Documentation: http://docs.travis-ci.com/user/languages/julia/
language: julia
os:
  - linux
julia:
  - 0.5
notifications:
  email: false
before_install:
  - sudo apt-get install gfortran -y  
script:
  - if [[ -a .git/shallow ]]; then git fetch --unshallow; fi
  - julia -e 'Pkg.clone(pwd()); Pkg.build("JFSM")'
  #- julia -e 'Pkg.clone(pwd()); Pkg.build("JFSM"); Pkg.test("JFSM"; coverage=true)'
#after_success:
  # push coverage results to Coveralls
#  - julia -e 'cd(Pkg.dir("JFSM")); Pkg.add("Coverage"); using Coverage; Coveralls.submit(Coveralls.process_folder())'
  # push coverage results to Codecov
#  - julia -e 'cd(Pkg.dir("JFSM")); Pkg.add("Coverage"); using Coverage; Codecov.submit(Codecov.process_folder())'
